"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _PayloadType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PayloadTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PayloadType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCALAR_STRING: _PayloadType.ValueType  # 0
    SCALAR_SHORT: _PayloadType.ValueType  # 1
    SCALAR_FLOAT: _PayloadType.ValueType  # 2
    SCALAR_ENUM: _PayloadType.ValueType  # 3
    SCALAR_BYTE: _PayloadType.ValueType  # 4
    SCALAR_INT: _PayloadType.ValueType  # 5
    SCALAR_DOUBLE: _PayloadType.ValueType  # 6
    WAVEFORM_STRING: _PayloadType.ValueType  # 7
    WAVEFORM_SHORT: _PayloadType.ValueType  # 8
    WAVEFORM_FLOAT: _PayloadType.ValueType  # 9
    WAVEFORM_ENUM: _PayloadType.ValueType  # 10
    WAVEFORM_BYTE: _PayloadType.ValueType  # 11
    WAVEFORM_INT: _PayloadType.ValueType  # 12
    WAVEFORM_DOUBLE: _PayloadType.ValueType  # 13
    V4_GENERIC_BYTES: _PayloadType.ValueType  # 14

class PayloadType(_PayloadType, metaclass=_PayloadTypeEnumTypeWrapper):
    """An enumeration that indicates what PB message should be used to unmarshall the following chunk of data
    This is a copy of ArchDBRTypes and the numbers must match the integermap in ArchDBRTypes for the reverse lookup to work
    Look at DBR2PBTypeMapping to see how we can construct a hashmap that unmarshalls an appropriate language type based on this enum.
    """

SCALAR_STRING: PayloadType.ValueType  # 0
SCALAR_SHORT: PayloadType.ValueType  # 1
SCALAR_FLOAT: PayloadType.ValueType  # 2
SCALAR_ENUM: PayloadType.ValueType  # 3
SCALAR_BYTE: PayloadType.ValueType  # 4
SCALAR_INT: PayloadType.ValueType  # 5
SCALAR_DOUBLE: PayloadType.ValueType  # 6
WAVEFORM_STRING: PayloadType.ValueType  # 7
WAVEFORM_SHORT: PayloadType.ValueType  # 8
WAVEFORM_FLOAT: PayloadType.ValueType  # 9
WAVEFORM_ENUM: PayloadType.ValueType  # 10
WAVEFORM_BYTE: PayloadType.ValueType  # 11
WAVEFORM_INT: PayloadType.ValueType  # 12
WAVEFORM_DOUBLE: PayloadType.ValueType  # 13
V4_GENERIC_BYTES: PayloadType.ValueType  # 14
Global___PayloadType: _TypeAlias = PayloadType  # noqa: Y015

@_typing.final
class FieldValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    val: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        val: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FieldValue: _TypeAlias = FieldValue  # noqa: Y015

@_typing.final
class ScalarString(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.str
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.str | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarString: _TypeAlias = ScalarString  # noqa: Y015

@_typing.final
class ScalarByte(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.bytes
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.bytes | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarByte: _TypeAlias = ScalarByte  # noqa: Y015

@_typing.final
class ScalarShort(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.int | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarShort: _TypeAlias = ScalarShort  # noqa: Y015

@_typing.final
class ScalarInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.int | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarInt: _TypeAlias = ScalarInt  # noqa: Y015

@_typing.final
class ScalarEnum(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.int | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarEnum: _TypeAlias = ScalarEnum  # noqa: Y015

@_typing.final
class ScalarFloat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.float
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.float | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarFloat: _TypeAlias = ScalarFloat  # noqa: Y015

@_typing.final
class ScalarDouble(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.float
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.float | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScalarDouble: _TypeAlias = ScalarDouble  # noqa: Y015

@_typing.final
class VectorString(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """No packed here as this is available only for primitive fields."""

    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.str] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorString: _TypeAlias = VectorString  # noqa: Y015

@_typing.final
class VectorChar(_message.Message):
    """VectorChar is the same as ScalarChar as we use ByteString for both"""

    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.bytes
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.bytes | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorChar: _TypeAlias = VectorChar  # noqa: Y015

@_typing.final
class VectorShort(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.int] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorShort: _TypeAlias = VectorShort  # noqa: Y015

@_typing.final
class VectorInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.int] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorInt: _TypeAlias = VectorInt  # noqa: Y015

@_typing.final
class VectorEnum(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.int] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorEnum: _TypeAlias = VectorEnum  # noqa: Y015

@_typing.final
class VectorFloat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.float] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorFloat: _TypeAlias = VectorFloat  # noqa: Y015

@_typing.final
class VectorDouble(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    @_builtins.property
    def val(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _abc.Iterable[_builtins.float] | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VectorDouble: _TypeAlias = VectorDouble  # noqa: Y015

@_typing.final
class V4GenericBytes(_message.Message):
    """A generic v4 container; we simply store the bytes as obtained from EPICS v4 as the val."""

    DESCRIPTOR: _descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: _builtins.int
    NANO_FIELD_NUMBER: _builtins.int
    VAL_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REPEATCOUNT_FIELD_NUMBER: _builtins.int
    FIELDVALUES_FIELD_NUMBER: _builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: _builtins.int
    USERTAG_FIELD_NUMBER: _builtins.int
    secondsintoyear: _builtins.int
    nano: _builtins.int
    val: _builtins.bytes
    severity: _builtins.int
    status: _builtins.int
    repeatcount: _builtins.int
    fieldactualchange: _builtins.bool
    userTag: _builtins.int
    """EPICS V4 user tag"""
    @_builtins.property
    def fieldvalues(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: _builtins.int | None = ...,
        nano: _builtins.int | None = ...,
        val: _builtins.bytes | None = ...,
        severity: _builtins.int | None = ...,
        status: _builtins.int | None = ...,
        repeatcount: _builtins.int | None = ...,
        fieldvalues: _abc.Iterable[Global___FieldValue] | None = ...,
        fieldactualchange: _builtins.bool | None = ...,
        userTag: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "userTag", b"userTag", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "userTag", b"userTag", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___V4GenericBytes: _TypeAlias = V4GenericBytes  # noqa: Y015

@_typing.final
class PayloadInfo(_message.Message):
    """A payload info is the first line in a chunk of data sent back to the client.
    It tells you how to unmarshall, the pvname and the year for the data
    It also has a lot of optional fields
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    PVNAME_FIELD_NUMBER: _builtins.int
    YEAR_FIELD_NUMBER: _builtins.int
    ELEMENTCOUNT_FIELD_NUMBER: _builtins.int
    UNUSED00_FIELD_NUMBER: _builtins.int
    UNUSED01_FIELD_NUMBER: _builtins.int
    UNUSED02_FIELD_NUMBER: _builtins.int
    UNUSED03_FIELD_NUMBER: _builtins.int
    UNUSED04_FIELD_NUMBER: _builtins.int
    UNUSED05_FIELD_NUMBER: _builtins.int
    UNUSED06_FIELD_NUMBER: _builtins.int
    UNUSED07_FIELD_NUMBER: _builtins.int
    UNUSED08_FIELD_NUMBER: _builtins.int
    UNUSED09_FIELD_NUMBER: _builtins.int
    HEADERS_FIELD_NUMBER: _builtins.int
    type: Global___PayloadType.ValueType
    pvname: _builtins.str
    year: _builtins.int
    elementCount: _builtins.int
    unused00: _builtins.float
    """Items from 5 to 14 are no longer to be used.
    Stick these into the headers using the field names
    For example, units comes in as EGU in the headers.
    """
    unused01: _builtins.float
    unused02: _builtins.float
    unused03: _builtins.float
    unused04: _builtins.float
    unused05: _builtins.float
    unused06: _builtins.float
    unused07: _builtins.float
    unused08: _builtins.float
    unused09: _builtins.str
    @_builtins.property
    def headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldValue]:
        """End of unused elements"""

    def __init__(
        self,
        *,
        type: Global___PayloadType.ValueType | None = ...,
        pvname: _builtins.str | None = ...,
        year: _builtins.int | None = ...,
        elementCount: _builtins.int | None = ...,
        unused00: _builtins.float | None = ...,
        unused01: _builtins.float | None = ...,
        unused02: _builtins.float | None = ...,
        unused03: _builtins.float | None = ...,
        unused04: _builtins.float | None = ...,
        unused05: _builtins.float | None = ...,
        unused06: _builtins.float | None = ...,
        unused07: _builtins.float | None = ...,
        unused08: _builtins.float | None = ...,
        unused09: _builtins.str | None = ...,
        headers: _abc.Iterable[Global___FieldValue] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["elementCount", b"elementCount", "pvname", b"pvname", "type", b"type", "unused00", b"unused00", "unused01", b"unused01", "unused02", b"unused02", "unused03", b"unused03", "unused04", b"unused04", "unused05", b"unused05", "unused06", b"unused06", "unused07", b"unused07", "unused08", b"unused08", "unused09", b"unused09", "year", b"year"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["elementCount", b"elementCount", "headers", b"headers", "pvname", b"pvname", "type", b"type", "unused00", b"unused00", "unused01", b"unused01", "unused02", b"unused02", "unused03", b"unused03", "unused04", b"unused04", "unused05", b"unused05", "unused06", b"unused06", "unused07", b"unused07", "unused08", b"unused08", "unused09", b"unused09", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PayloadInfo: _TypeAlias = PayloadInfo  # noqa: Y015
