"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PayloadType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PayloadTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PayloadType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCALAR_STRING: _PayloadType.ValueType  # 0
    SCALAR_SHORT: _PayloadType.ValueType  # 1
    SCALAR_FLOAT: _PayloadType.ValueType  # 2
    SCALAR_ENUM: _PayloadType.ValueType  # 3
    SCALAR_BYTE: _PayloadType.ValueType  # 4
    SCALAR_INT: _PayloadType.ValueType  # 5
    SCALAR_DOUBLE: _PayloadType.ValueType  # 6
    WAVEFORM_STRING: _PayloadType.ValueType  # 7
    WAVEFORM_SHORT: _PayloadType.ValueType  # 8
    WAVEFORM_FLOAT: _PayloadType.ValueType  # 9
    WAVEFORM_ENUM: _PayloadType.ValueType  # 10
    WAVEFORM_BYTE: _PayloadType.ValueType  # 11
    WAVEFORM_INT: _PayloadType.ValueType  # 12
    WAVEFORM_DOUBLE: _PayloadType.ValueType  # 13
    V4_GENERIC_BYTES: _PayloadType.ValueType  # 14

class PayloadType(_PayloadType, metaclass=_PayloadTypeEnumTypeWrapper):
    """An enumeration that indicates what PB message should be used to unmarshall the following chunk of data
    This is a copy of ArchDBRTypes and the numbers must match the integermap in ArchDBRTypes for the reverse lookup to work
    Look at DBR2PBTypeMapping to see how we can construct a hashmap that unmarshalls an appropriate language type based on this enum.
    """

SCALAR_STRING: PayloadType.ValueType  # 0
SCALAR_SHORT: PayloadType.ValueType  # 1
SCALAR_FLOAT: PayloadType.ValueType  # 2
SCALAR_ENUM: PayloadType.ValueType  # 3
SCALAR_BYTE: PayloadType.ValueType  # 4
SCALAR_INT: PayloadType.ValueType  # 5
SCALAR_DOUBLE: PayloadType.ValueType  # 6
WAVEFORM_STRING: PayloadType.ValueType  # 7
WAVEFORM_SHORT: PayloadType.ValueType  # 8
WAVEFORM_FLOAT: PayloadType.ValueType  # 9
WAVEFORM_ENUM: PayloadType.ValueType  # 10
WAVEFORM_BYTE: PayloadType.ValueType  # 11
WAVEFORM_INT: PayloadType.ValueType  # 12
WAVEFORM_DOUBLE: PayloadType.ValueType  # 13
V4_GENERIC_BYTES: PayloadType.ValueType  # 14
global___PayloadType = PayloadType

@typing.final
class FieldValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    name: builtins.str
    val: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        val: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "val", b"val"]) -> None: ...

global___FieldValue = FieldValue

@typing.final
class ScalarString(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.str
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.str | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarString = ScalarString

@typing.final
class ScalarByte(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.bytes
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.bytes | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarByte = ScalarByte

@typing.final
class ScalarShort(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.int | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarShort = ScalarShort

@typing.final
class ScalarInt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.int | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarInt = ScalarInt

@typing.final
class ScalarEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.int | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarEnum = ScalarEnum

@typing.final
class ScalarFloat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.float
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.float | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarFloat = ScalarFloat

@typing.final
class ScalarDouble(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.float
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.float | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___ScalarDouble = ScalarDouble

@typing.final
class VectorString(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """No packed here as this is available only for primitive fields."""

    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.str] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorString = VectorString

@typing.final
class VectorChar(google.protobuf.message.Message):
    """VectorChar is the same as ScalarChar as we use ByteString for both"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.bytes
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.bytes | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorChar = VectorChar

@typing.final
class VectorShort(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.int] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorShort = VectorShort

@typing.final
class VectorInt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.int] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorInt = VectorInt

@typing.final
class VectorEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.int] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorEnum = VectorEnum

@typing.final
class VectorFloat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.float] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorFloat = VectorFloat

@typing.final
class VectorDouble(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    @property
    def val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: collections.abc.Iterable[builtins.float] | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "val", b"val"]) -> None: ...

global___VectorDouble = VectorDouble

@typing.final
class V4GenericBytes(google.protobuf.message.Message):
    """A generic v4 container; we simply store the bytes as obtained from EPICS v4 as the val."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDSINTOYEAR_FIELD_NUMBER: builtins.int
    NANO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REPEATCOUNT_FIELD_NUMBER: builtins.int
    FIELDVALUES_FIELD_NUMBER: builtins.int
    FIELDACTUALCHANGE_FIELD_NUMBER: builtins.int
    USERTAG_FIELD_NUMBER: builtins.int
    secondsintoyear: builtins.int
    nano: builtins.int
    val: builtins.bytes
    severity: builtins.int
    status: builtins.int
    repeatcount: builtins.int
    fieldactualchange: builtins.bool
    userTag: builtins.int
    """EPICS V4 user tag"""
    @property
    def fieldvalues(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]: ...
    def __init__(
        self,
        *,
        secondsintoyear: builtins.int | None = ...,
        nano: builtins.int | None = ...,
        val: builtins.bytes | None = ...,
        severity: builtins.int | None = ...,
        status: builtins.int | None = ...,
        repeatcount: builtins.int | None = ...,
        fieldvalues: collections.abc.Iterable[global___FieldValue] | None = ...,
        fieldactualchange: builtins.bool | None = ...,
        userTag: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "userTag", b"userTag", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldactualchange", b"fieldactualchange", "fieldvalues", b"fieldvalues", "nano", b"nano", "repeatcount", b"repeatcount", "secondsintoyear", b"secondsintoyear", "severity", b"severity", "status", b"status", "userTag", b"userTag", "val", b"val"]) -> None: ...

global___V4GenericBytes = V4GenericBytes

@typing.final
class PayloadInfo(google.protobuf.message.Message):
    """A payload info is the first line in a chunk of data sent back to the client.
    It tells you how to unmarshall, the pvname and the year for the data
    It also has a lot of optional fields
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    PVNAME_FIELD_NUMBER: builtins.int
    YEAR_FIELD_NUMBER: builtins.int
    ELEMENTCOUNT_FIELD_NUMBER: builtins.int
    UNUSED00_FIELD_NUMBER: builtins.int
    UNUSED01_FIELD_NUMBER: builtins.int
    UNUSED02_FIELD_NUMBER: builtins.int
    UNUSED03_FIELD_NUMBER: builtins.int
    UNUSED04_FIELD_NUMBER: builtins.int
    UNUSED05_FIELD_NUMBER: builtins.int
    UNUSED06_FIELD_NUMBER: builtins.int
    UNUSED07_FIELD_NUMBER: builtins.int
    UNUSED08_FIELD_NUMBER: builtins.int
    UNUSED09_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    type: global___PayloadType.ValueType
    pvname: builtins.str
    year: builtins.int
    elementCount: builtins.int
    unused00: builtins.float
    """Items from 5 to 14 are no longer to be used.
    Stick these into the headers using the field names
    For example, units comes in as EGU in the headers.
    """
    unused01: builtins.float
    unused02: builtins.float
    unused03: builtins.float
    unused04: builtins.float
    unused05: builtins.float
    unused06: builtins.float
    unused07: builtins.float
    unused08: builtins.float
    unused09: builtins.str
    @property
    def headers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldValue]:
        """End of unused elements"""

    def __init__(
        self,
        *,
        type: global___PayloadType.ValueType | None = ...,
        pvname: builtins.str | None = ...,
        year: builtins.int | None = ...,
        elementCount: builtins.int | None = ...,
        unused00: builtins.float | None = ...,
        unused01: builtins.float | None = ...,
        unused02: builtins.float | None = ...,
        unused03: builtins.float | None = ...,
        unused04: builtins.float | None = ...,
        unused05: builtins.float | None = ...,
        unused06: builtins.float | None = ...,
        unused07: builtins.float | None = ...,
        unused08: builtins.float | None = ...,
        unused09: builtins.str | None = ...,
        headers: collections.abc.Iterable[global___FieldValue] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["elementCount", b"elementCount", "pvname", b"pvname", "type", b"type", "unused00", b"unused00", "unused01", b"unused01", "unused02", b"unused02", "unused03", b"unused03", "unused04", b"unused04", "unused05", b"unused05", "unused06", b"unused06", "unused07", b"unused07", "unused08", b"unused08", "unused09", b"unused09", "year", b"year"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["elementCount", b"elementCount", "headers", b"headers", "pvname", b"pvname", "type", b"type", "unused00", b"unused00", "unused01", b"unused01", "unused02", b"unused02", "unused03", b"unused03", "unused04", b"unused04", "unused05", b"unused05", "unused06", b"unused06", "unused07", b"unused07", "unused08", b"unused08", "unused09", b"unused09", "year", b"year"]) -> None: ...

global___PayloadInfo = PayloadInfo
