include:
  - 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml'
  - 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml'

.runner_tags: &runner_tags
  tags:
    - docker

stages:
  - check
  - build
  - test
  - release

test-python36:
  <<: *runner_tags
  stage: test
  image: python:3.6
  before_script:
    - pip install -e .[tests]
  script:
    - pytest -v

test-python37:
  <<: *runner_tags
  stage: test
  image: python:3.7
  before_script:
    - pip install -e .[tests]
  script:
    - pytest --cov=epicsarchiver -v

test-python38:
  <<: *runner_tags
  stage: test
  image: python:3.8
  before_script:
    - pip install -e .[tests]
  script:
    - pytest -v

pages:
  <<: *runner_tags
  stage: release
  image: python:3.7
  before_script:
    - pip install .[docs]
  script:
    - sphinx-build -M html docs docs/_build
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  only:
    - tags
