
variables:
  CONTAINER_TEST_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  TWINE_REPOSITORY_URL: https://artifactory.esss.lu.se/artifactory/api/pypi/ics-pypi
  TWINE_USERNAME: gitlab
  TWINE_PASSWORD: secret
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


include:
  - project: "ics-infrastructure/gitlab-ci-yml"
    file: "PreCommit.gitlab-ci.yml"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache/pip

stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy


before_script:
  - python --version  # For debugging
  - pip install hatch

.parallel:
  parallel:
    matrix:
      - PY_VERSION: ["3.10", "3.11", "3.12", "3.13", "3.14"]

default:
  image: python:3.10
  tags:
    - docker

run-pre-commit:
  before_script:
    - python --version  # For debugging
    - pip install hatch

test:
  stage: test
  image: python:$PY_VERSION
  script:
    - hatch test -i py=$PY_VERSION --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  parallel: !reference [.parallel, parallel]

jupyter-check:
  stage: test
  script:
    - hatch run jupyter-check


cov:
  stage: analyse
  script:
    - hatch test -c
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


lint:
  stage: check
  script:
    - hatch fmt --check

lint-types:
  stage: check
  script:
    - hatch run types:check

lint-docs:
  stage: check
  script:
    - hatch run docs:check

build:
  stage: build
  script:
    - hatch build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - hatch run docs:build
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - tags


release-pypi-package:
  stage: release
  before_script:
    - pip install twine
  script:
    - twine upload dist/* --verbose
  only:
    - tags
