[version]
source = "vcs"

[version.raw-options]
git_describe_command = ["git", "describe", "--dirty", "--tags", "--long"]

[build.hooks.vcs]
version-file = "epicsarchiver/_version.py"

[build.targets.sdist]
include = ["/epicsarchiver", "/tests"]

[build.targets.wheel]
packages = ["epicsarchiver"]

[envs.default.scripts]
protoc-gen = "protoc -I=epicsarchiver --python_out=epicsarchiver --mypy_out=epicsarchiver epicsarchiver/retrieval/EPICSEvent.proto"
docs-check = "hatch run docs:check"
type-check = "hatch run types:check"
jupyter-check = "hatch run jupyter:check"
all = ["hatch fmt --check", "type-check", "jupyter-check", "docs-check", "hatch test"]

[[envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[envs.hatch-test]
extra-dependencies = [
  "pytest-asyncio",
  "responses",
  "aioresponses",
  "pytest-mock",
  "pytest-aiohttp",
]

[envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage xml"

[envs.types]
extra-dependencies = [
  "mypy",
  "mypy-protobuf",
  "pytest",
  "pytest-asyncio",
  "responses",
  "aioresponses",
  "pytest-mock",
  "pytest-aiohttp",
  "typing-extensions",
  "types-requests",
  "types-python-dateutil",
  "types-protobuf",
]

[envs.types.scripts]
check-src = "mypy --install-types --non-interactive {args:./epicsarchiver}"
check-tests = "mypy --install-types --non-interactive --explicit-package-bases {args:./tests}"
check = ["check-src", "check-tests"]

[envs.docs]
extra-dependencies = [
  "sphinx",
  "sphinx-copybutton>=0.5.1",
  "sphinx-click",
  "sphinx-autobuild",
  "sphinx-autoapi>=3.6.0",
  "sphinx_rtd_theme",
  "myst_nb",
]

[envs.docs.scripts]
build = ["make -C docs html"]
check = ['make -C docs html SPHINXOPTS="-W --keep-going"']
live = ["sphinx-autobuild docs/source docs/build/html"]
clean = ["make -C docs clean html"]

[envs.jupyter]
extra-dependencies = [
  "notebook>=7.1.2",
  "nbval>=0.11.0",
  "matplotlib>=3.8.3"
]

[envs.jupyter.scripts]
check = ['py.test --nbval tests/jupyter/']

[envs.hatch-static-analysis]
dependencies = ["ruff==0.15.0"]
config-path = "ruff.toml"
