[build-system]
build-backend = "hatchling.build"

requires = [ "hatch-vcs>=0.3", "hatchling>=1.24.2" ]

[project]
name = "epicsarchiver-retrieval-client"
description = "A python library for retrieving data from the EPICS Archiver Appliance."
readme = "README.md"
keywords = [ "archiver", "epics", "retrieval" ]
authors = [
  { name = "Benjamin Bertrand" },
  { name = "Sky Brewer", email = "sky.brewer@ess.eu" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]

dependencies = [
  "httpx>=0.27",
  "protobuf>=7,<8",
  "pytz>=2024.1",
  "typing-extensions>=4.12",
]

optional-dependencies.all = [ "epicsarchiver-retrieval-client[async,cli,polars,sync]" ]
optional-dependencies.async = [ "aiohttp>=3" ]
optional-dependencies.cli = [ "click>=8", "rich>=13" ]
optional-dependencies.polars = [ "polars>=1" ]
optional-dependencies.sync = [ "requests>=2" ]
urls.Source = "https://github.com/archiver-appliance/epicsarchiver-retrieval-client"
scripts.arch-retrieval = "epicsarchiver.command:cli"

[tool.ruff]
extend = "ruff.toml"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

[tool.coverage.paths]
epicsarchiver = [ "epicsarchiver" ]
tests = [ "tests" ]

[tool.coverage.report]
exclude_lines = [ "no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:" ]
show_missing = true

[tool.coverage.run]
source_pkgs = [ "epicsarchiver", "tests" ]
branch = true
parallel = true
omit = [ "epicsarchiver/__about__.py" ]

[tool.mypy]
strict = true
python_version = "3.10"
