target-version = "py38"
line-length = 88
exclude = [
  "epicsarchiver/retrieval/EPICSEvent_pb2.py",
  "epicsarchiver/retrieval/EPICSEvent_pb2.pyi",
  "docs/source/conf.py",
  "*.ipynb"
]
preview = true

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = ["ALL"
]
ignore = [
  "ANN101", "ANN102", "ANN204", "ANN401", "COM812", "CPY001", "D412", "ISC001",
]

[lint.per-file-ignores]
"**/scripts/*" = [
  "INP001",
  "T201",
]
"**/tests/**/*" = [
  "PLC1901",
  "PLR2004",
  "PLR6301",
  "S",
  "TID252",
]
"tests/**/*" = ["PLR2004", "S101", "TID252", "D", "SLF001", "INP001", "PLC2701"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["py_epicsarchiver"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"
